export const Product = [
  {
    id: 13,
    Title: "TCL 55 QM6K Series 4K UHD HDR QDMini LED",
    Cat: "tv",
    Price: "549",
    Img: [
      "/img/tv1-1.jpg",
      "/img/tv1-2.jpg",
      "/img/tv1-3.jpg",
      "/img/tv1-4.jpg",
      "/img/tv1-1.jpg",
      "/img/tv1-2.jpg",
      "/img/tv1-3.jpg",
      "/img/tv1-4.jpg",
    ],
    SubCat: "hot",
    Brand: "TCL",
    Model: "55QM6KWeb",
    WebCode: "18985112",
    Rating: 4.2,
    NumRev: 1530,
    State: "Available",
    Stock: 12,

    Overview: [
      "The TCL 55 QM6K delivers sharp 4K UHD quality with bright, high-contrast QD-Mini LED and support for Dolby Vision/HDR10+. Its smooth motion, slim design, and smart features provide a modern, immersive viewing experience.",
    ],
    Delivery: [],
    Specifications: [
      "Display: 55-inch QD-Mini LED panel, 4K UHD (3840 × 2160), HDR10+ & Dolby Vision.",
      "Audio: Dual speakers with Dolby Audio processing.",
      "Smart Features: Google TV OS, Wi-Fi, built-in Voice Assistant support.",
      "Connectivity: 3 HDMI ports, 2 USB ports, Bluetooth, and Optical audio output.",
    ],
    customerReviews: [
      {
        name: "Emma Johnson",
        date: "2025-03-15",
        rating: 5,
        observation:
          "Absolutely love this TV! The colors are vibrant and the motion is incredibly smooth. Setup was super easy.",
      },
      {
        name: "Liam Smith",
        date: "2025-03-12",
        rating: 4,
        observation:
          "Great picture quality and HDR performance. The built-in apps are convenient, though the remote could be better.",
      },
      {
        name: "Olivia Brown",
        date: "2025-03-10",
        rating: 4,
        observation:
          "Excellent value for the price. The sound is good but I recommend a soundbar for a more immersive experience.",
      },
      {
        name: "Noah Davis",
        date: "2025-03-08",
        rating: 5,
        observation:
          "I’m impressed with this TCL TV. The QD-Mini LED makes a huge difference in contrast and brightness. Highly recommend!",
      },
    ],
  },

  {
    id: 14,
    Title: "Hisense 55 QD6QF Series 4K UHD HDR QLED Fire ",
    Cat: "tv",
    Price: "379",
    Img: [
      "/img/tv2-1.jpg",
      "/img/tv2-2.jpg",
      "/img/tv2-3.jpg",
      "/img/tv2-4.jpg",
    ],
    SubCat: "Trending",
    Brand: "Hisense",
    Model: "55QD6QF",
    WebCode: "19335537",
    Rating: 3.7,
    NumRev: 2840,
    State: "Sold out",
  },
  {
    id: 15,
    Title: "Samsung 75 U7900F Series 4K UHD HDR LED Tizen ",
    Cat: "tv",
    Price: "796",
    Img: [
      "/img/tv3-1.jpg",
      "/img/tv3-2.jpg",
      "/img/tv3-3.jpg",
      "/img/tv3-4.jpg",
    ],
    SubCat: "Bestsellers",
    Brand: "Samsung",
    Model: "UN75U7900FFXZC",
    WebCode: "19204872",
    Rating: 4.8,
    NumRev: 3987,
    State: "Available",
  },
  {
    id: 16,
    Title: "Insignia 55 4K UHD HDR LED Fire TV ",
    Cat: "tv",
    Price: "399",
    DisountedPrice: "180",
    Img: [
      "/img/tv4-1.jpg",
      "/img/tv4-2.jpg",
      "/img/tv4-3.jpg",
      "/img/tv4-4.jpg",
    ],
    SubCat: "Specialoffers",
    Brand: "Insignia",
    Model: "NS55F501CA26",
    WebCode: "19192120",
    Rating: 4,
    NumRev: 674,
    State: "Available",
  },
  {
    id: 17,
    Title: "Samsung 55 U7900F Series 4K UHD HDR LED Tizen ",
    Cat: "tv",
    Price: "479",
    Img: [
      "/img/tv5-1.jpg",
      "/img/tv5-2.jpg",
      "/img/tv5-3.jpg",
      "/img/tv5-4.jpg",
      "/img/tv5-1.jpg",
      "/img/tv5-2.jpg",
      "/img/tv5-3.jpg",
      "/img/tv5-4.jpg",
      "/img/tv5-1.jpg",
      "/img/tv5-2.jpg",
      "/img/tv5-3.jpg",
      "/img/tv5-4.jpg",
    ],
    SubCat: "",
    Brand: "Samsung",
    Model: "UN55U7900FFXZC",
    WebCode: "19204876",
    Rating: 4.6,
    NumRev: 2101,
    State: "Sold out",
    Stock: 51,
  },
  {
    id: 18,
    Title: "Samsung 50 U8000F Series 4K UHD HDR LED Tizen ",
    Cat: "tv",
    Price: "497",
    Img: [
      "/img/tv6-1.jpg",
      "/img/tv6-2.jpg",
      "/img/tv6-3.jpg",
      "/img/tv6-4.jpg",
    ],
    SubCat: "",
    Brand: "Samsung",
    Model: "UN50U8000FFXZC",
    WebCode: "19204864",
    Rating: 4.3,
    NumRev: 389,
    State: "Available",
  },
  {
    id: 19,
    Title: "Insignia 50 4K UHD HDR LCD Fire TV ",
    Cat: "tv",
    Price: "349",
    Img: [
      "/img/tv7-1.jpg",
      "/img/tv7-2.jpg",
      "/img/tv7-3.jpg",
      "/img/tv7-4.jpg",
    ],
    SubCat: "hot",
    Brand: "Insignia",
    Model: "NS50F502CA26",
    WebCode: "18931314",
    Rating: 4.1,
    NumRev: 2503,
    State: "Sold out",
  },
  {
    id: 20,
    Title: "Samsung 65 QN70F Series 4K UHD HDR Neo QLED Tizen ",
    Cat: "tv",
    Price: "1399",
    Img: [
      "/img/tv8-1.jpg",
      "/img/tv8-2.jpg",
      "/img/tv8-3.jpg",
      "/img/tv8-4.jpg",
    ],
    SubCat: "",
    Brand: "Samsung",
    Model: "QN65QN70FAFXZC",
    WebCode: "19206111",
    Rating: 4.9,
    NumRev: 1123,
    State: "Available",
  },
  {
    id: 21,
    Title: "Refurbished Good Xbox Series S 512GB CONSOLE",
    Cat: "consoles",
    Price: "379",
    Img: [
      "/img/game1-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "",
    Brand: "Microsoft",
    Model: "RRS00001",
    WebCode: "17077094",
    Rating: 4.0,
    NumRev: 2315,
    State: "Sold out",
  },
  {
    id: 22,
    Title: "Refurbished Good Xbox One S 500GB Console",
    Cat: "consoles",
    Price: "247",
    Img: [
      "/img/game2-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "",
    Brand: "Microsoft",
    Model: "1681",
    WebCode: "16662539",
    Rating: 3.8,
    NumRev: 1624,
    State: "Available",
  },
  {
    id: 23,
    Title: "Open Box  PlayStation 5 Slim Console",
    Cat: "consoles",
    Price: "599",
    DisountedPrice: "349",
    Img: [
      "/img/game3-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "Specialoffers",
    Brand: "Playstation",
    Model: " 1000039655",
    WebCode: "17650702",
    Rating: 4.9,
    NumRev: 3889,
    State: "Available",
  },
  {
    id: 24,
    Title: "Open Box  PlayStation 5 Slim Digital Edition Console",
    Cat: "consoles",
    Price: "529",
    Img: [
      "/img/game4-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "Trending",
    Brand: "Playstation",
    Model: "1000039669",
    WebCode: "17650703",
    Rating: 4.5,
    NumRev: 1077,
    State: "Sold out",
  },
  {
    id: 25,
    Title: "Open Box  PlayStation 5 Pro Console 120fps 4K",
    Cat: "consoles",
    Price: "804",
    Img: [
      "/img/game5-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "Bestsellers",
    Brand: "Playstation",
    Model: "1000046547",
    WebCode: "18905772",
    Rating: 5.0,
    NumRev: 2765,
    State: "Available",
  },
  {
    id: 26,
    Title: "Refurbished Fair  Xbox One S 2TB Console & 4K Bluray Player",
    Cat: "consoles",
    Price: "359",
    Img: [
      "/img/game6-1.jpg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "hot",
    Brand: "Samsung",
    Model: "2DZ00002",
    WebCode: "19182425",
    Rating: 3.5,
    NumRev: 864,
    State: "Available",
  },
  {
    id: 27,
    Title: "Samsung Galaxy A56 5G 128GB Awesome Graphite ",
    Cat: "phones",
    Price: "519",
    Img: [
      "/img/phone1-1.jpg",
      "/img/phone1-2.jpg",
      "/img/phone1-3.jpg",
      "/img/phone1-4.jpg",
    ],
    SubCat: "",
    Brand: "Samsung",
    Model: "SMA566WZKAXAC",
    WebCode: "19362154",
    Rating: 4.0,
    NumRev: 2044,
    State: "Sold out",
  },
  {
    id: 28,
    Title: "Open Box  Samsung Galaxy S25 128GB Silver Shadow ",
    Cat: "phones",
    Price: "693",
    DisountedPrice: "449",
    Img: [
      "/img/phone2-1.jpeg",
      "/img/phone2-2.jpeg",
      "/img/phone2-3.jpeg",
      "/img/phone2-4.jpeg",
    ],
    SubCat: "Specialoffers",
    Brand: "Samsung",
    Model: "SMS931W",
    WebCode: "19183118",
    Rating: 4.7,
    NumRev: 3560,
    State: "Available",
  },
  {
    id: 29,
    Title: "Open Box  Apple iPhone 15 512GB Yellow ",
    Cat: "phones",
    Price: "359",
    DisountedPrice: "169",
    Img: [
      "/img/phone3-1.jpeg",
      "/img/phone3-2.jpeg",
      "/img/phone3-3.jpeg",
      "/img/phone3-4.jpeg",
    ],
    SubCat: "Specialoffers",
    Brand: "Apple",
    Model: "MTMW3VC/A",
    WebCode: "17462394",
    Rating: 4.8,
    NumRev: 3891,
    State: "Sold out",
  },
  {
    id: 30,
    Title: "Apple iPhone 16 Pro 128GB Desert Titanium ",
    Cat: "phones",
    Price: "1449",
    Img: [
      "/img/phone4-1.jpg",
      "/img/phone4-2.jpg",
      "/img/phone4-3.jpg",
      "/img/phone4-4.jpg",
    ],
    SubCat: "Trending",
    Brand: "Apple",
    Model: "MYMX3VC/A",
    WebCode: "18391197",
    Rating: 4.9,
    NumRev: 2555,
    State: "Available",
  },
  {
    id: 31,
    Title: "Refurbished Excellent Apple iPhone 14 128GB  Midnight ",
    Cat: "phones",
    Price: "489",
    Img: [
      "/img/phone5-1.jpeg",
      "/img/phone5-2.jpeg",
      "/img/phone5-3.jpeg",
      "/img/phone5-4.jpeg",
    ],
    SubCat: "hot",
    Brand: "Apple",
    Model: "MPUD3VC/A",
    WebCode: "16553704",
    Rating: 4.3,
    NumRev: 1190,
    State: "Available",
  },
  {
    id: 32,
    Title: "OnePlus Nord N30 5G 128GB Grey ",
    Cat: "phones",
    Price: "299",
    Img: [
      "/img/phone6-1.jpg",
      "/img/phone6-2.jpg",
      "/img/phone6-3.jpg",
      "/img/phone6-4.jpg",
    ],
    SubCat: "",
    Brand: "OnePlus",
    Model: "CPH2513",
    WebCode: "17147473",
    Rating: 4.1,
    NumRev: 468,
    State: "Sold out",
  },
  {
    id: 33,
    Title: "Samsung Galaxy A16 5G 128GB Blue Black ",
    Cat: "phones",
    Price: "199",
    Img: [
      "/img/phone7-1.jpg",
      "/img/phone7-2.jpg",
      "/img/phone7-3.jpg",
      "/img/phone7-4.jpg",
    ],
    SubCat: "",
    Brand: "Samsung",
    Model: "SMA166WZKAXAC",
    WebCode: "18896891",
    Rating: 3.9,
    NumRev: 2178,
    State: "Available",
  },
  {
    id: 34,
    Title: "ASUS TUF F15 15.6 144Hz Gaming Laptop",
    Cat: "computers",
    Price: "1299",
    Img: [
      "/img/laptop1-1.jpg",
      "/img/laptop1-2.jpg",
      "/img/laptop1-3.jpg",
      "/img/laptop1-4.jpg",
    ],
    SubCat: "",
    Brand: "Asus",
    Model: "FX507VVBH74CB",
    WebCode: "18928810",
    Rating: 4.4,
    NumRev: 1975,
    State: "Available",
  },
  {
    id: 35,
    Title: "ASUS ROG Strix G16 16 165Hz Gaming Laptop",
    Cat: "computers",
    Price: "1499",
    Img: [
      "/img/laptop2-1.jpg",
      "/img/laptop2-2.jpg",
      "/img/laptop2-3.jpg",
      "/img/laptop2-4.jpg",
    ],
    SubCat: "",
    Brand: "Asus",
    Model: "G614JVBS74CB",
    WebCode: "18928809",
    Rating: 4.7,
    NumRev: 2670,
    State: "Sold out",
  },
  {
    id: 36,
    Title: "ASUS TUF Gaming A16 16 Gaming Laptop",
    Cat: "computers",
    Price: "1099",
    Img: [
      "/img/laptop3-1.jpg",
      "/img/laptop3-2.jpg",
      "/img/laptop3-3.jpg",
      "/img/laptop3-4.jpg",
    ],
    SubCat: "hot",
    Brand: "Asus",
    Model: "FA607NUBS53CBWeb",
    WebCode: "18933108",
    Rating: 4.2,
    NumRev: 1340,
    State: "Available",
  },
  {
    id: 37,
    Title: "Acer Nitro V 15.6 AMD Ryzen 5 Gaming Laptop",
    Cat: "computers",
    Price: "999",
    Img: [
      "/img/laptop4-1.jpg",
      "/img/laptop4-2.jpg",
      "/img/laptop4-3.jpg",
      "/img/laptop4-4.jpg",
    ],
    SubCat: "",
    Brand: "Acer",
    Model: "SMANV1541R93X",
    WebCode: "19274603",
    Rating: 4.1,
    NumRev: 1905,
    State: "Sold out",
  },
  {
    id: 38,
    Title: "ASUS ROG Strix G18 2024 18 WQXGA 240Hz Gaming Laptop",
    Cat: "computers",
    Price: "2199",
    Img: [
      "/img/laptop5-1.jpg",
      "/img/laptop5-2.jpg",
      "/img/laptop5-3.jpg",
      "/img/laptop5-4.jpg",
    ],
    SubCat: "Trending",
    Brand: "Asus",
    Model: "G814JVRBS91CB",
    WebCode: "17700713",
    Rating: 4.9,
    NumRev: 3768,
    State: "Available",
  },
  {
    id: 39,
    Title: "MSI Thin 15 15.6 Gaming Laptop Cosmos Grey",
    Cat: "computers",
    Price: "1399",
    Img: [
      "/img/laptop6-1.jpg",
      "/img/laptop6-2.jpg",
      "/img/laptop6-3.jpg",
      "/img/laptop6-4.jpg",
    ],
    SubCat: "",
    Brand: "MSI",
    Model: "B13VE1299CA",
    WebCode: "17685417",
    Rating: 4.3,
    NumRev: 2210,
    State: "Available",
  },
  {
    id: 40,
    Title: "ASUS ROG Strix 16 Gaming Laptop Eclipse Grey",
    Cat: "computers",
    Price: "2999",
    Img: [
      "/img/laptop7-1.jpg",
      "/img/laptop7-2.jpg",
      "/img/laptop7-3.jpg",
      "/img/laptop7-4.jpg",
    ],
    SubCat: "",
    Brand: "ASUS",
    Model: "G615LMBS96CBWeb",
    WebCode: "19335010",
    Rating: 5.0,
    NumRev: 3899,
    State: "Sold out",
  },
  {
    id: 41,
    Title: "Open Box  ASUS ROG Strix G16 16 165Hz Gaming Laptop",
    Cat: "computers",
    Price: "1199",
    Img: [
      "/img/laptop8-1.jpeg",
      "/img/laptop8-2.jpg",
      "/img/laptop8-3.jpg",
      "/img/laptop8-4.jpg",
      "/img/laptop8-1.jpeg",
      "/img/laptop8-2.jpg",
      "/img/laptop8-3.jpg",
      "/img/laptop8-4.jpg",
    ],
    SubCat: "",
    Brand: "ASUS",
    Model: "G614JVBS74CB",
    WebCode: "19416224",
    Rating: 4.5,
    NumRev: 1922,
    State: "Available",
  },
  {
    id: 42,
    Title: "Sony Alpha a7 III FullFrame Mirrorless Vlogger Camera ",
    Cat: "cameras",
    Price: "2199",
    DisountedPrice: "1889",
    Img: [
      "/img/camera1-1.jpg",
      "/img/camera1-2.jpg",
      "/img/camera1-3.jpg",
      "/img/camera1-4.jpg",
    ],
    SubCat: "Specialoffers",
    Brand: "Sony",
    Model: "ILCE7M3K/B",
    WebCode: "12383793",
    Rating: 5,
    NumRev: 2720,
    State: "Available",
  },
  {
    id: 43,
    Title: "Panasonic LUMIX ZS99S WiFi 20.3 MP 30x Optical Zoom",
    Cat: "cameras",
    Price: "699",
    Img: [
      "/img/camera2-1.jpg",
      "/img/camera2-2.jpg",
      "/img/camera2-3.jpg",
      "/img/camera2-4.jpg",
    ],
    SubCat: "",
    Brand: "Lumix",
    Model: "DCZS99K",
    WebCode: "19206463",
    Rating: 4.2,
    NumRev: 1670,
    State: "Sold out",
  },
  {
    id: 44,
    Title: "Canon PowerShot G7 X Mark III WiFi 20.1MP 4.2x ",
    Cat: "cameras",
    Price: "1149",
    Img: [
      "/img/camera3-1.jpg",
      "/img/camera3-2.jpg",
      "/img/camera3-3.jpg",
      "/img/camera3-4.jpg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "3637C001",
    WebCode: "13799023",
    Rating: 4.4,
    NumRev: 1432,
    State: "Available",
  },
  {
    id: 45,
    Title: "Fujifilm X100VI 40.2MP Advanced Compact Digital",
    Cat: "cameras",
    Price: "2159",
    Img: [
      "/img/camera4-1.jpg",
      "/img/camera4-2.jpg",
      "/img/camera4-3.jpg",
      "/img/camera4-4.jpg",
    ],
    SubCat: "",
    Brand: "Fujifilm",
    Model: "X100VI",
    WebCode: "17732069",
    Rating: 4.7,
    NumRev: 3610,
    State: "Available",
  },
  {
    id: 46,
    Title: "Sony Alpha 7 IV FullFrame Mirrorless 2870mm Lens Kit",
    Cat: "cameras",
    Price: "2199",
    Img: [
      "/img/camera5-1.jpg",
      "/img/camera5-2.jpg",
      "/img/camera5-3.jpg",
      "/img/camera5-4.jpg",
    ],
    SubCat: "Trending",
    Brand: "Sony",
    Model: "ILCE7M4K/B",
    WebCode: "15779885",
    Rating: 4.8,
    NumRev: 1989,
    State: "Sold out",
  },
  {
    id: 47,
    Title: "Canon PowerShot SX740 Digital Camera w/40x Optical Zoom ",
    Cat: "cameras",
    Price: "1249",
    Img: [
      "/img/camera6-1.jpeg",
      "/img/camera6-2.jpeg",
      "/img/camera6-3.jpeg",
      "/img/camera6-4.jpeg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "2955C001",
    WebCode: "13021650",
    Rating: 4.3,
    NumRev: 2784,
    State: "Available",
  },
  {
    id: 48,
    Title: "Sony Alpha 6400 APSC Mirrorless Camera with 1650mm",
    Cat: "cameras",
    Price: "1199",
    Img: [
      "/img/camera7-1.jpg",
      "/img/camera7-2.jpg",
      "/img/camera7-3.jpg",
      "/img/camera7-4.jpg",
    ],
    SubCat: "",
    Brand: "Sony",
    Model: "ILCE6400KB",
    WebCode: "19184501",
    Rating: 4.5,
    NumRev: 1322,
    State: "Available",
  },
  {
    id: 49,
    Title: "Canon PowerShot SX740 HS WiFi 20.3MP 40x Optical Zoom",
    Cat: "cameras",
    Price: "699",
    Img: [
      "/img/camera8-1.jpg",
      "/img/camera8-2.jpg",
      "/img/camera8-3.jpg",
      "/img/camera8-4.jpg",
    ],
    SubCat: "",
    Rating: 4.5,
    Brand: "Canon",
    NumRev: 1322,
    Model: "2955",
    State: "Available",
    WebCode: "12383478",
  },
  {
    id: 50,
    Title: "Canon EOS Rebel T7 DSLR Camera with 1855mm Lens Kit",
    Cat: "cameras",
    Price: "619",
    Img: [
      "/img/camera9-1.jpg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "2727C003",
    WebCode: "12383478",
    Rating: 3.8,
    NumRev: 105,
    State: "Available",
  },
  {
    id: 51,
    Title: "Canon EOS Rebel SL3 DSLR Camera with 1855mm Lens Kit",
    Cat: "cameras",
    Price: "929",
    Img: [
      "/img/camera10-1.jpg",
      "/img/camera10-2.jpg",
      "/img/camera10-3.jpg",
      "/img/camera10-4.jpg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "3453C002",
    WebCode: "15130960",
    Rating: 1.5,
    NumRev: 100,
    State: "Available",
  },
  {
    id: 52,
    Title: "Canon EOS Rebel T7 DSLR Camera with 1855mm Lens Kit",
    Cat: "cameras",
    Price: "639",
    Img: [
      "/img/camera10-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "2727C003",
    WebCode: "16571071",
    Rating: 4.5,
    NumRev: 120,
    State: "Sold out",
  },
  {
    id: 53,
    Title: "Canon EOS Rebel SL3 DSLR Camera with 1855mm Lens Kit",
    Cat: "cameras",
    Price: "849",
    Img: [
      "/img/camera11-1.jpg",
      "/img/camera11-2.jpg",
      "/img/camera11-3.jpg",
      "/img/camera11-4.jpg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "3453C002",
    WebCode: "13528848",
    Rating: 3.1,
    NumRev: 50,
    State: "Available",
  },
  {
    id: 54,
    Title: "Canon EOS 7D Mark II DSLR Camera Body Only",
    Cat: "cameras",
    Price: "2024",
    Img: [
      "/img/camera12-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "",
    Brand: "Canon",
    Model: "9128B003",
    WebCode: "14674978",
    Rating: 4.9,
    NumRev: 159,
    State: "Available",
  },
  {
    id: 55,
    Title: "Nikon D7500 DSLR Camera Body Only Open Box",
    Cat: "cameras",
    Price: "1487",
    Img: [
      "/img/camera13-1.jpg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "",
    Brand: "Nikon",
    Model: "NKD7500BDOB",
    WebCode: "13888890",
    Rating: 2.5,
    NumRev: 12,
    State: "Available",
  },
  {
    id: 56,
    Title: "Nikon D780 DSLR Camera with 24120mm AFS VR Lens Kit",
    Cat: "cameras",
    Price: "3349",
    Img: [
      "/img/camera14-1.jpg",
      "/img/camera14-2.jpg",
      "/img/camera14-3.jpg",
      "/img/camera14-4.jpg",
    ],
    SubCat: "",
    Brand: "Nikon",
    Model: "D780",
    WebCode: "14547430",
    Rating: 2.5,
    NumRev: 650,
    State: "Available",
  },
  {
    id: 57,
    Title: "Panasonic Lumix G9 II Mirrorless Camera",
    Cat: "cameras",
    Price: "2199",
    Img: [
      "/img/camera14-1.jpg",
      "/img/camera14-2.jpg",
      "/img/camera14-3.jpg",
      "/img/camera14-4.jpg",
    ],
    SubCat: "Bestsellers",
    Brand: "Panasonic",
    Model: "DCG9M2",
    WebCode: "17341635",
    Rating: 4.8,
    NumRev: 286,
    State: "Available",
  },
  {
    id: 58,
    Title: 'LG 65" QNED evo AI QNED85 4K UHD HDR MiniLED Smart TV',
    Cat: "tv",
    Price: "999",
    Img: [
      "/img/tv9-1.jpg",
      "/img/tv9-2.jpg",
      "/img/tv9-3.jpg",
      "/img/tv9-4.jpg",
    ],
    SubCat: "",
    Brand: "LG",
    Model: "65QNED85AYA",
    WebCode: "19290004",
    Rating: 2.6,
    NumRev: 29,
    State: "Available",
  },
  {
    id: 59,
    Title: 'LG 65" UT7000 Series 4K UHD HDR LED webOS Smart TV',
    Cat: "tv",
    Price: "549",
    Img: [
      "/img/tv10-1.jpg",
      "/img/tv10-2.jpg",
      "/img/tv10-3.jpg",
      "/img/tv10-4.jpg",
    ],
    SubCat: "",
    Brand: "LG",
    Model: "65UT7000PUA",
    WebCode: "18247900",
    Rating: 4.4,
    NumRev: 315,
    State: "Available",
  },
  {
    id: 60,
    Title: 'TCL 65" Q65 Series 4K UHD HDR QLED Smart Google TV',
    Cat: "tv",
    Price: "589",
    Img: [
      "/img/tv11-1.jpg",
      "/img/tv11-2.jpg",
      "/img/tv11-3.jpg",
      "/img/tv11-4.jpg",
    ],
    SubCat: "",
    Brand: "TCL",
    Model: "65Q651GCA",
    WebCode: "17856038",
    Rating: 2.7,
    NumRev: 380,
    State: "Available",
  },
  {
    id: 61,
    Title: 'TCL Q5 Class 65" Q550F Series 4K UHD HDR QLED Fire',
    Cat: "tv",
    Price: "549",
    Img: [
      "/img/tv12-1.jpg",
      "/img/tv12-2.jpg",
      "/img/tv12-3.jpg",
      "/img/tv12-4.jpg",
    ],
    SubCat: "",
    Brand: "TCL",
    Model: "65Q550FCA",
    WebCode: "19276964",
    Rating: 4.7,
    NumRev: 5222,
    State: "Available",
  },
  {
    id: 62,
    Title: 'Hisense 65" QD7QFM Series 4K UHD HDR MiniLED',
    Cat: "tv",
    Price: "629",
    Img: [
      "/img/tv13-1.jpg",
      "/img/tv13-2.jpg",
      "/img/tv13-3.jpg",
      "/img/tv13-4.jpg",
    ],
    SubCat: "",
    Brand: "Hisense",
    Model: "65QD7QFM",
    WebCode: "19327248",
    Rating: 4,
    NumRev: 92,
    State: "Available",
  },
  {
    id: 63,
    Title: 'LG 65" UA7700 Series AI UA77 4K UHD HDR LCD Smart TV',
    Cat: "tv",
    Price: "699",
    Img: [
      "/img/tv14-1.jpg",
      "/img/tv14-2.jpg",
      "/img/tv14-3.jpg",
      "/img/tv14-4.jpg",
    ],
    SubCat: "",
    Brand: "LG",
    Model: "65UA7700PUB",
    WebCode: "19330423",
    Rating: 4.3,
    NumRev: 1478,
    State: "Available",
  },
  {
    id: 64,
    Title: 'LG 65" 4K UHD HDR QNED webOS Smart TV',
    Cat: "tv",
    Price: "849",
    Img: [
      "/img/tv15-1.jpg",
      "/img/tv15-2.jpg",
      "/img/tv15-3.jpg",
      "/img/tv15-4.jpg",
    ],
    SubCat: "",
    Brand: "LG",
    Model: "65QNED80TUC",
    WebCode: "17924078",
    Rating: 4.6,
    NumRev: 238,
    State: "Sold out",
  },
  {
    id: 65,
    Title: 'LG 65" QNED80AUA Series QNED AI QNED80 4K UHD',
    Cat: "tv",
    Price: "879",
    Img: [
      "/img/tv16-1.jpg",
      "/img/tv16-2.jpg",
      "/img/tv16-3.jpg",
      "/img/tv16-4.jpg",
    ],
    SubCat: "",
    Brand: "LG",
    Model: "65QNED80AUA",
    WebCode: "19292390",
    Rating: 4.7,
    NumRev: 121,
    State: "Sold out",
  },
  {
    id: 66,
    Title: "Google Pixel 9a 128GB Obsidian Unlocked",
    Cat: "phones",
    Price: "529",
    Img: [
      "/img/phone8-1.jpg",
      "/img/phone8-2.jpg",
      "/img/phone8-3.jpg",
      "/img/phone8-4.jpg",
    ],
    SubCat: "",
    Brand: "Google",
    Model: "GXQ96",
    WebCode: "18933640",
    Rating: 4.7,
    NumRev: 57,
    State: "Available",
  },
  {
    id: 67,
    Title: "Google Pixel 10 Pro Fold 256GB Moonstone Unlocked",
    Cat: "phones",
    Price: "2399",
    Img: [
      "/img/phone9-1.jpg",
      "/img/phone9-2.jpg",
      "/img/phone9-3.jpg",
      "/img/phone9-4.jpg",
    ],
    SubCat: "",
    Brand: "Google",
    Model: "GPF10P256",
    WebCode: "19363152",
    Rating: 4.8,
    NumRev: 133,
    State: "Sold out",
  },
  {
    id: 68,
    Title: "Freedom Mobile Apple iPhone 17 Pro 256GB Cosmic Orange",
    Cat: "phones",
    Price: "299",
    Img: [
      "/img/phone10-1.jpg",
      "/img/phone10-2.jpg",
      "/img/phone10-3.jpg",
      "/img/phone10-4.jpg",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "A3103",
    WebCode: "19418777",
    Rating: 4.9,
    NumRev: 42,
    State: "Available",
  },
  {
    id: 69,
    Title: "Apple iPhone 15 128GB Green Unlocked",
    Cat: "phones",
    Price: "1129",
    Img: [
      "/img/phone11-1.jpg",
      "/img/phone11-2.jpg",
      "/img/phone11-3.jpg",
      "/img/phone11-4.jpg",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "A3090",
    WebCode: "17230350",
    Rating: 1.6,
    NumRev: 1367,
    State: "Sold out",
  },
  {
    id: 70,
    Title: "Rogers Apple iPhone 17 Pro Max 256GB Silver",
    Cat: "phones",
    Price: "784",
    Img: [
      "/img/phone12-1.jpg",
      "/img/phone12-2.jpg",
      "/img/phone12-3.jpg",
      "/img/phone12-4.jpg",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "A3111",
    WebCode: "19418894",
    Rating: 2.9,
    NumRev: 55,
    State: "Available",
  },
  {
    id: 71,
    Title: "Refurbished Excellent Apple iPhone 12 64GB Black",
    Cat: "phones",
    Price: "299",
    Img: [
      "/img/phone13-1.jpeg",
      "/img/phone13-2.png",
      "/img/phone13-3.png",
      "/img/phone13-4.png",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "A2403",
    WebCode: "15336571",
    Rating: 4.5,
    NumRev: 280,
    State: "Available",
  },
  {
    id: 72,
    Title: "Freedom Mobile Apple iPhone 17 256GB Sage",
    Cat: "phones",
    Price: "449",
    Img: [
      "/img/phone14-1.jpg",
      "/img/phone14-2.jpg",
      "/img/phone14-3.jpg",
      "/img/phone14-4.jpg",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "A3100",
    WebCode: "19418639",
    Rating: 4.8,
    NumRev: 327,
    State: "Sold out",
  },
  {
    id: 73,
    Title: "Open Box Samsung Galaxy S23 128GB Phantom Black",
    Cat: "phones",
    Price: "369",
    Img: [
      "/img/phone15-1.jpeg",
      "/img/phone15-2.jpeg",
      "/img/phone15-3.jpeg",
      "/img/phone15-4.jpeg",
    ],
    SubCat: "Bestsellers",
    Brand: "Samsung",
    Model: "SMS911W",
    WebCode: "16709009",
    Rating: 4.8,
    NumRev: 1258,
    State: "Available",
  },
  {
    id: 74,
    Title: "ASUS TUF Gaming F16 16 Gaming Laptop  Mecha Grey",
    Cat: "computers",
    Price: "949",
    Img: [
      "/img/laptop8-1.jpeg",
      "/img/laptop8-2.jpg",
      "/img/laptop8-3.jpg",
      "/img/laptop8-4.jpg",
    ],
    SubCat: "",
    Brand: "Asus",
    Model: " FX607VJBB53CB",
    WebCode: "19339454",
    Rating: 4.5,
    NumRev: 1258,
    State: "Available",
  },
  {
    id: 75,
    Title: "ASUS ROG Strix SCAR 18 Gaming Laptop  Off Black",
    Cat: "computers",
    Price: "6999",
    Img: [
      "/img/laptop9-1.jpg",
      "/img/laptop9-2.jpg",
      "/img/laptop9-3.jpg",
      "/img/laptop9-4.jpg",
    ],
    SubCat: "",
    Brand: "Asus",
    Model: "G835LXXS99CA",
    WebCode: " 19186642",
    Rating: 4.8,
    NumRev: 53,
    State: "Available",
  },
  {
    id: 76,
    Title: "Apple MacBook Air 13.6 Touch ID 2025  Midnight",
    Cat: "computers",
    Price: "1449",
    Img: [
      "/img/laptop10-1.jpg",
      "/img/laptop10-2.jpg",
      "/img/laptop10-3.jpg",
      "/img/laptop10-4.jpg",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "MW133LL/A",
    WebCode: "19205141",
    Rating: 2.8,
    NumRev: 125,
    State: "Sold out",
  },
  {
    id: 77,
    Title: "Refurbished Good  Apple MacBook Pro Touch Bar 16",
    Cat: "computers",
    Price: "649",
    Img: [
      "/img/laptop11-1.jpeg",
      "/img/game1-2.jpeg",
      "/img/game1-3.jpeg",
      "/img/game1-4.jpeg",
    ],
    SubCat: "Bestsellers",
    Brand: "Apple",
    Model: "SMS911W",
    WebCode: "14405255",
    Rating: 5,
    NumRev: 1258,
    State: "Sold out",
  },
  {
    id: 78,
    Title: "Open Box Apple MacBook Pro 13.3 Touch Bar 2020  Gray",
    Cat: "computers",
    Price: "799",
    Img: [
      "/img/laptop12-1.jpeg",
      "/img/laptop12-2.jpeg",
      "/img/laptop12-3.jpeg",
      "/img/laptop12-4.jpeg",
    ],
    SubCat: "",
    Brand: "Apple",
    Model: "MWP72LL/A",
    WebCode: "15311920",
    Rating: 1.8,
    NumRev: 14,
    State: "Available",
  },
  {
    id: 79,
    Title: "Refurbished Excellent Microsoft Surface Laptop",
    Cat: "computers",
    Price: "649",
    Img: [
      "/img/laptop13-1.jpeg",
      "/img/laptop13-2.jpeg",
      "/img/laptop13-3.jpeg",
      "/img/laptop13-4.jpeg",
    ],
    SubCat: "",
    Brand: "Microsoft",
    Model: "Surface Laptop 3 13",
    WebCode: "18975885",
    Rating: 3.8,
    NumRev: 58,
    State: "Sold out",
  },

  /* CONSOLES */

  {
    id: 80,
    Title: "PlayStation 5 DualSense Wireless Controller",
    Cat: "consoles",
    Price: "99",
    Img: [
      "/img/game7-1.jpg",
      "/img/game7-2.jpg",
      "/img/game7-3.jpg",
      "/img/game7-4.jpg",
    ],
    SubCat: "",
    Brand: "PlayStation",
    Model: "1000046930",
    WebCode: "18481636",
    Rating: 4.4,
    NumRev: 14,
    State: "Sold out",
  },
  {
    id: 81,
    Title: "Meta Quest 3S 128GB VR Headset",
    Cat: "consoles",
    Price: "399",
    Img: [
      "/img/game8-1.jpg",
      "/img/game8-2.jpg",
      "/img/game8-3.jpg",
      "/img/game8-4.jpg",
    ],
    SubCat: "",
    Brand: "Meta",
    Model: "SK100020301",
    WebCode: "19206091",
    Rating: 4.8,
    NumRev: 308,
    State: "Available",
  },
  {
    id: 82,
    Title: "PlayStation 5 Slim Console",
    Cat: "consoles",
    Price: "649",
    Img: [
      "/img/game9-1.jpg",
      "/img/game9-2.jpg",
      "/img/game9-3.jpg",
      "/img/game9-1.jpg",
    ],
    SubCat: "",
    Brand: "PlayStation",
    Model: "1000039655",
    WebCode: "17477496",
    Rating: 1.8,
    NumRev: 45,
    State: "Sold out",
  },
  {
    id: 83,
    Title: "Refurbished Good Sony PlayStation 5 PS5 Console Disc",
    Cat: "consoles",
    Price: "464",
    Img: [
      "/img/game10-1.jpeg",
      "/img/game9-2.jpg",
      "/img/game9-3.jpg",
      "/img/game9-1.jpg",
    ],
    SubCat: "refurbished",
    Brand: "Sony",
    Model: "CFI1015A",
    WebCode: "19481537",
    Rating: 4.5,
    NumRev: 120,
    State: "Available",
  },
  {
    id: 84,
    Title: "PlayStation 5 DualSense Wireless Controller  Midnight",
    Cat: "consoles",
    Price: "94",
    Img: [
      "/img/game11-1.jpg",
      "/img/game11-2.jpg",
      "/img/game11-3.jpg",
      "/img/game11-4.jpg",
    ],
    SubCat: "",
    Brand: "PlayStation",
    Model: "1000046931",
    WebCode: "17905836",
    Rating: 4.6,
    NumRev: 280,
    State: "Sold out",
  },
  {
    id: 85,
    Title: "Logitech G29 Driving Force Racing Wheel for PlayStation",
    Cat: "consoles",
    Price: "299",
    Img: [
      "/img/game12-1.jpg",
      "/img/game12-2.jpg",
      "/img/game12-3.jpg",
      "/img/game12-4.jpg",
    ],
    SubCat: "",
    Brand: "Logitech",
    Model: "941000110",
    WebCode: "10383067",
    Rating: 2.7,
    NumRev: 1540,
    State: "Available",
  },
  {
    id: 86,
    Title: "PlayStation 5 DualSense Wireless Controller",
    Cat: "consoles",
    Price: "39",
    Img: [
      "/img/game13-1.jpg",
      "/img/game13-2.jpg",
      "/img/game13-3.jpg",
      "/img/game13-4.jpg",
    ],
    SubCat: "",
    Brand: "PlayStation",
    Model: "1000046932",
    WebCode: "14962276",
    Rating: 5,
    NumRev: 2180,
    State: "Sold out",
  },
];

export const Data = [
  {
    image: "/img/Homexbox-Photoroom.png",
    title: "Enter epic worlds and play freely",
    discount: "Save 50% now",
    subtext: "Level Up Your Gaming",
  },
  {
    image: "/img/camera9-Photoroom.png",
    title: "Capture life’s moments with perfect clarity",
    discount: "Get 50% off today",
    subtext: "Capture Life Perfectly",
  },
  {
    image: "/img/laptop11-Photoroom.png",
    title: "Power meets portability for modern life",
    discount: "Up to 50% off",
    subtext: "Stay connected",
  },
];
