const Product = [
  /*Hot deal product*/
  {
    id: 1,
    Title: "Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB",
    Cat: "Tablet",
    Price: "723",
    Img: "./img/tp1.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "TabS6Lite128",
    Code: "10001",
  },
  {
    id: 2,
    Title: "Waterproof Tracker Pedometer Smart watch",
    Cat: "Smart Watch",
    Price: "168",
    Img: "./img/tp2.jpg",
    HotDeal: "",
    Brand: "FitTrack",
    Model: "WT-PD01",
    Code: "10002",
  },
  {
    id: 3,
    Title: "Cancelling Headphones Wireless",
    Cat: "Headphone",
    Price: "49",
    Img: "./img/tp3.jpg",
    HotDeal: "",
    Brand: "SoundMax",
    Model: "SM-WH49",
    Code: "10003",
  },
  {
    id: 4,
    Title: "Professional Camera 4K Digital Video Camera",
    Cat: "Camera",
    Price: "1049",
    Img: "./img/tp4.jpg",
    HotDeal: "",
    Brand: "Canon",
    Model: "4KDV-C1049",
    Code: "10004",
  },
  {
    id: 5,
    Title: "Mini Portable PD 22.5W Fast Charging Powerbank",
    Cat: "Powerbank",
    Price: "49",
    Img: "./img/tp5.jpg",
    HotDeal: "",
    Brand: "Anker",
    Model: "A-PD225",
    Code: "10005",
  },
  {
    id: 6,
    Title: "CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB",
    Cat: "Electronics",
    Price: "156",
    Img: "./img/tp6.png",
    HotDeal: "",
    Brand: "CoolerMaster",
    Model: "CM-RGB156",
    Code: "10006",
  },
  {
    id: 7,
    Title: "Playstation 4 2TB Slim Gaming Console",
    Cat: "Gaming",
    Price: "2098",
    Img: "./img/tp7.jpg",
    HotDeal: "",
    Brand: "Sony",
    Model: "PS4Slim2TB",
    Code: "10007",
  },
  {
    id: 8,
    Title: "Mini Portable Mobile Phone Powerbank for iphone",
    Cat: "Electronics",
    Price: "386",
    Img: "./img/tp8.jpg",
    type: "powerbank",
    Brand: "Mophie",
    Model: "MP-IPH386",
    Code: "10008",
  },
  {
    id: 9,
    Title: "Microsoft Surface Pro 8-13' Touchscreen",
    Cat: "Tablet",
    Price: "693",
    Img: "./img/p9.jpg",
    type: "tablet",
    Brand: "Microsoft",
    Model: "SurfacePro8",
    Code: "10009",
  },
  {
    id: 10,
    Title: "Playstation 4 2TB Slim Gaming Console",
    Cat: "Gaming",
    Price: "5036",
    Img: "./img/p10.jpg",
    type: "console",
    Brand: "Sony",
    Model: "PS4SlimPro",
    Code: "10010",
  },
  {
    id: 11,
    Title: "Echo Show 5 (2nd Gen) Adjustable Stand | Charcoal",
    Cat: "Electronics",
    Price: "198",
    Img: "./img/p11.jpg",
    type: "smart-display",
    Brand: "Amazon",
    Model: "EchoShow5-2G",
    Code: "10011",
  },
  {
    id: 12,
    Title: "Echo Dot smart speaker",
    Cat: "Electronics",
    Price: "793",
    Img: "./img/p12.jpg",
    type: "speaker",
    Brand: "Amazon",
    Model: "EchoDotGen4",
    Code: "10012",
  } /*----Tv & Audio-----*/,
  {
    id: 13,
    Title:
      "TCL 55 QM6K Series 4K UHD HDR QD-Mini LED Smart Google TV (55QM6K) - 2025",
    Cat: "Tv & Audio",
    Price: "549",
    Img: "./img/tv1.jpg",
    HotDeal: "",
    Brand: "TCL",
    Model: "55QM6KWeb",
    Code: "18985112",
  },
  {
    id: 14,
    Title:
      "Hisense 55 QD6QF Series 4K UHD HDR QLED Fire TV Smart TV (55QD6QF) - 2025",
    Cat: "Tv & Audio",
    Price: "379",
    Img: "./img/tv2.jpg",
    HotDeal: "",
    Brand: "Hisense",
    Model: "55QD6QF",
    WebCode: "19335537",
  },
  {
    id: 15,
    Title:
      "Samsung 75 U7900F Series 4K UHD HDR LED Tizen Smart TV (UN75U7900FFXZC) - 2025",
    Cat: "Tv & Audio",
    Price: "796",
    Img: "./img/tv3.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "UN75U7900FFXZC",
    WebCode: "19204872",
  },
  {
    id: 16,
    Title: "Insignia 55 4K UHD HDR LED Fire TV Smart TV (NS-55F501CA26) - 2025",
    Cat: "Tv & Audio",
    Price: "399",
    Img: "./img/tv4.jpg",
    HotDeal: "",
    Brand: "Insignia",
    Model: "NS-55F501CA26",
    WebCode: "19192120",
  },
  {
    id: 17,
    Title:
      "Samsung 55 U7900F Series 4K UHD HDR LED Tizen Smart TV (UN55U7900FFXZC) - 2025",
    Cat: "Tv & Audio",
    Price: "479",
    Img: "./img/tv5.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "UN55U7900FFXZC",
    WebCode: "19204876",
  },
  {
    id: 18,
    Title:
      "Samsung 50 U8000F Series 4K UHD HDR LED Tizen Smart TV (UN50U8000FFXZC) - 2025",
    Cat: "Tv & Audio",
    Price: "497",
    Img: "./img/tv6.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "UN50U8000FFXZC",
    WebCode: "19204864",
  },
  {
    id: 19,
    Title: "Insignia 50 4K UHD HDR LCD Fire TV Smart TV (NS-50F502CA26) - 2024",
    Cat: "Tv & Audio",
    Price: "349",
    Img: "./img/tv7.jpg",
    HotDeal: "true",
    Brand: "Insignia",
    Model: "NS-50F502CA26",
    WebCode: "18931314",
  },
  {
    id: 20,
    Title:
      "Samsung 65 QN70F Series 4K UHD HDR Neo QLED Tizen Smart TV (QN65QN70FAFXZC) - 2025",
    Cat: "Tv & Audio",
    Price: "1399",
    Img: "./img/tv8.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "QN65QN70FAFXZC",
    WebCode: "19206111",
  },
  /*----Game and Consoles-----*/ {
    id: 21,
    Title: "Refurbished (Good) - Xbox Series S 512GB CONSOLE",
    Cat: "Game and Consoles",
    Price: "379",
    Img: "./img/game1.jpeg",
    HotDeal: "",
    Brand: "Microsoft",
    Model: "RRS-00001",
    WebCode: "17077094",
  },
  {
    id: 22,
    Title: "Refurbished (Good) - Xbox One S 500GB Console",
    Cat: "Game and Consoles",
    Price: "247",
    Img: "./img/game2.jpeg",
    HotDeal: "",
    Brand: "Microsoft",
    Model: "1681",
    WebCode: "16662539",
  },
  {
    id: 23,
    Title: "Open Box - PlayStation 5 Slim Console",
    Cat: "Game and Consoles",
    Price: "599",
    Img: "./img/game3.jpeg",
    HotDeal: "",
    Brand: "Playstation",
    Model: " 1000039655",
    WebCode: "17650702",
  },
  {
    id: 24,
    Title: "Open Box - PlayStation 5 Slim Digital Edition Console",
    Cat: "Game and Consoles",
    Price: "529",
    Img: "./img/game4.jpeg",
    HotDeal: "",
    Brand: "Playstation",
    Model: "1000039669",
    WebCode: "17650703",
  },
  {
    id: 25,
    Title: "Open Box - PlayStation 5 Pro Console",
    Cat: "Game and Consoles",
    Price: "804",
    Img: "./img/game5.jpeg",
    HotDeal: "",
    Brand: "Playstation",
    Model: "1000046547",
    WebCode: "18905772",
  },
  {
    id: 26,
    Title: "Refurbished (Fair) - Xbox One S 2TB Console & 4K Blu-ray Player",
    Cat: "Game and Consoles",
    Price: "359",
    Img: "./img/game6.jpg",
    HotDeal: "true",
    Brand: "Samsung",
    Model: "2DZ-00002",
    WebCode: "19182425",
  },
  /*----Phones & Tablettes-----*/ {
    id: 27,
    Title: "Samsung Galaxy A56 5G 128GB - Awesome Graphite - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "519",
    Img: "./img/phone1.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "SM-A566WZKAXAC",
    WebCode: "19362154",
  },
  {
    id: 28,
    Title: "Open Box - Samsung Galaxy S25 128GB - Silver Shadow - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "693",
    Img: "./img/phone2.jpeg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "SM-S931W",
    WebCode: "19183118",
  },
  {
    id: 29,
    Title: "Open Box - Apple iPhone 15 512GB - Yellow - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "359",
    Img: "./img/phone3.jpeg",
    HotDeal: "",
    Brand: "Apple",
    Model: "MTMW3VC/A",
    WebCode: "17462394",
  },
  {
    id: 30,
    Title: "Apple iPhone 16 Pro 128GB - Desert Titanium - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "1449",
    Img: "./img/phone4.jpg",
    HotDeal: "",
    Brand: "Apple",
    Model: "MYMX3VC/A",
    WebCode: "18391197",
  },
  {
    id: 31,
    Title:
      "Refurbished (Excellent) - Apple iPhone 14 128GB - Midnight - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "489",
    Img: "./img/phone5.jpeg",
    HotDeal: "true",
    Brand: "Apple",
    Model: "MPUD3VC/A",
    WebCode: "16553704",
  },
  {
    id: 32,
    Title: "OnePlus Nord N30 5G 128GB - Grey - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "299",
    Img: "./img/phone6.jpg",
    HotDeal: "",
    Brand: "OnePlus",
    Model: "CPH2513",
    WebCode: "17147473",
  },
  {
    id: 33,
    Title: "Samsung Galaxy A16 5G 128GB - Blue Black - Unlocked",
    Cat: "Phones & Tablettes",
    Price: "199",
    Img: "./img/phone7.jpg",
    HotDeal: "",
    Brand: "Samsung",
    Model: "SM-A166WZKAXAC",
    WebCode: "18896891",
  } /*----Computer & Laptop-----*/,
  {
    id: 34,
    Title:
      "ASUS TUF F15 15.6 144Hz Gaming Laptop (Intel Core i7-13620H/16GB RAM/1TB SSD/RTX 4060/Windows 11 Home)",
    Cat: "Computer & Laptop",
    Price: "1299",
    Img: "./img/laptop1.jpg",
    HotDeal: "",
    Brand: "Asus",
    Model: "FX507VV-BH74-CB",
    WebCode: "18928810",
  },
  {
    id: 35,
    Title:
      "ASUS ROG Strix G16 16 165Hz Gaming Laptop (Intel Core i7-13650HX/16GB RAM/1TB SSD/RTX 4060/Win 11)",
    Cat: "Computer & Laptop",
    Price: "1499",
    Img: "./img/laptop2.jpg",
    HotDeal: "",
    Brand: "Asus",
    Model: "G614JV-BS74-CB",
    WebCode: "18928809",
  },
  {
    id: 36,
    Title:
      "ASUS TUF Gaming A16 16 Gaming Laptop - Mecha Grey (AMD Ryzen 5 7535HS/16GB RAM/512GB SSD/RTX 4050)",
    Cat: "Computer & Laptop",
    Price: "1099",
    Img: "./img/laptop3.jpg",
    HotDeal: "true",
    Brand: "Asus",
    Model: "FA607NU-BS53-CBWeb",
    WebCode: "18933108",
  },
  {
    id: 37,
    Title:
      "Acer Nitro V 15.6 Gaming Laptop (AMD Ryzen 5 7535HS/8GB RAM/512GB SSD/RTX3050/Windows 11)",
    Cat: "Computer & Laptop",
    Price: "999",
    Img: "./img/laptop4.jpg",
    HotDeal: "",
    Brand: "Acer",
    Model: "SM-ANV15-41-R93X",
    WebCode: "19274603",
  },
  {
    id: 38,
    Title:
      "ASUS ROG Strix G18 (2024) 18 WQXGA 240Hz Gaming Laptop (Intel Core i9-14900HX/1TB SSD/32GB RAM/RTX 4060)",
    Cat: "Computer & Laptop",
    Price: "2199",
    Img: "./img/laptop5.jpg",
    HotDeal: "",
    Brand: "Asus",
    Model: "G814JVR-BS91-CB",
    WebCode: "17700713",
  },
  {
    id: 39,
    Title:
      "MSI Thin 15 15.6 Gaming Laptop - Cosmos Grey (Intel Core i7-13620H/512GB/16GB RAM/GeForce RTX 4050)",
    Cat: "Computer & Laptop",
    Price: "1399",
    Img: "./img/laptop6.jpg",
    HotDeal: "",
    Brand: "MSI",
    Model: "B13VE-1299CA",
    WebCode: "17685417",
  },
  {
    id: 40,
    Title:
      "ASUS ROG Strix 16 Gaming Laptop -Eclipse Grey (Intel Core Ultra 9 275HX/32GB RAM/1TB SSD/RTX 5060/Win 11 Home)",
    Cat: "Computer & Laptop",
    Price: "2999",
    Img: "./img/laptop7.jpg",
    HotDeal: "",
    Brand: "ASUS",
    Model: "G615LM-BS96-CBWeb",
    WebCode: "19335010",
  },
  {
    id: 41,
    Title:
      "Open Box - ASUS ROG Strix G16 16 165Hz Gaming Laptop (Intel Core i7-13650HX/16GB RAM/1TB SSD/RTX 4060/Win 11)",
    Cat: "Computer & Laptop",
    Price: "1199",
    Img: "./img/laptop8.jpeg",
    HotDeal: "",
    Brand: "ASUS",
    Model: "G614JV-BS74-CB",
    WebCode: "19416224",
  } /*----Cameras-----*/,
  {
    id: 42,
    Title:
      "Sony Alpha a7 III Full-Frame Mirrorless Vlogger Camera with 28-70mm OSS Lens Kit",
    Cat: "Cameras",
    Price: "2199",
    Img: "./img/camera1.jpg",
    HotDeal: "",
    Brand: "Sony",
    Model: "ILCE7M3K/B",
    WebCode: "12383793",
  },
  {
    id: 43,
    Title:
      "Panasonic LUMIX ZS99S Wi-Fi 20.3 MP 30x Optical Zoom 4K Video Digital Camera - Black",
    Cat: "Cameras",
    Price: "699",
    Img: "./img/camera2.jpg",
    HotDeal: "",
    Brand: "Lumix",
    Model: "DCZS99K",
    WebCode: "19206463",
  },
  {
    id: 44,
    Title:
      "Canon PowerShot G7 X Mark III Wi-Fi 20.1MP 4.2x Optical Zoom Digital Camera - Black",
    Cat: "Cameras",
    Price: "1149",
    Img: "./img/camera3.jpg",
    HotDeal: "",
    Brand: "Canon",
    Model: "3637C001",
    WebCode: "13799023",
  },
  {
    id: 45,
    Title: "Fujifilm X100VI 40.2MP Advanced Compact Digital Camera - Black",
    Cat: "Cameras",
    Price: "2159",
    Img: "./img/camera4.jpeg",
    HotDeal: "",
    Brand: "Fujifilm",
    Model: "X100VI",
    WebCode: "17732069",
  },
  {
    id: 46,
    Title: "Sony Alpha 7 IV Full-Frame Mirrorless Camera with 28-70mm Lens Kit",
    Cat: "Cameras",
    Price: "2199",
    Img: "./img/camera5.jpg",
    HotDeal: "",
    Brand: "Sony",
    Model: "ILCE7M4K/B",
    WebCode: "15779885",
  },
  {
    id: 47,
    Title:
      "Canon PowerShot SX740 Digital Camera w/40x Optical Zoom & 3 Inch Tilt LCD - 4K Video, Wi-Fi, NFC, Bluetooth Enabled (Black)",
    Cat: "Cameras",
    Price: "1249",
    Img: "./img/camera6.jpeg",
    HotDeal: "",
    Brand: "Canon",
    Model: "2955C001",
    WebCode: "13021650",
  },
  {
    id: 48,
    Title:
      "Sony Alpha 6400 APS-C Mirrorless Camera with 16-50mm Lens Kit - Black",
    Cat: "Cameras",
    Price: "1199",
    Img: "./img/camera7.jpg",
    HotDeal: "",
    Brand: "Sony",
    Model: "ILCE6400KB",
    WebCode: "19184501",
  },
  {
    id: 49,
    Title:
      "Canon PowerShot SX740 HS Wi-Fi 20.3MP 40x Optical Zoom Digital Camera - Black",
    Cat: "Cameras",
    Price: "699",
    Img: "./img/camera8.jpg",
    HotDeal: "",
    Brand: "Canon",
    Model: "2955C013",
    WebCode: "12874677",
  },
];
export default Product;
